### ISSUE TITLE
MySql - supported?

### ISSUE THREAD

**Issue by cmjchrisjones** [PaulMiami/Authenticator#1]
Hi Paul, I'm trying to implement this in my ASP.NET Core 1.1 website using MySql (Pomelo provider), and I have a seed method to add a couple of users, however, I'm getting the following exception thrown:

    Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while updating the entries. See the inner exception for details.'
    
    NotSupportedException: Parameter type HashAlgorithmType (DbType: Byte) not currently supported. Value: SHA1

I believe I have done everything as required, even using the AuthenticatorUserManager, 
     var userManager = app.ApplicationServices.GetService<AuthenticatorUserManager<ApplicationUser>>();

Is there any work around you can think of to make this work?

**Comment by PaulMiami** [comment]
Hi,

I haven't tested with MySQL, let me give it a try and I'll let you know what I found out

**Comment by cmjchrisjones** [comment]
Thanks @PaulMiami, let me know if you need any further information and I will try and supply what you need

**Comment by PaulMiami** [comment]
This is a bug on how Pomelo handles mapping enum values.
The enum "HashAlgorithmType" inherits from byte and the underlying MySqlConnector library gets confused because the DbType.Byte is not matching a clr type byte.
It was already reported in this PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#78.
I have create a PR to fix that PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#211

**Comment by cmjchrisjones** [comment]
Thanks @PaulMiami, I'm now eagerly awaiting for the Pomelo guys to approve your PR so I can hopefully start using this :)

**Comment by PaulMiami** [comment]
Just did  a quick test with the [latest preview build from Pomelo](https://www.myget.org/Package/Details/pomelo?packageType=nuget&packageId=Pomelo.EntityFrameworkCore.MySql) and it seems to work fine
